import type { FieldConfig } from '@/components/forms/EntityForm';

export interface EntityConfig {
  slug: string;
  arabicName: string;
  description: string;
  icon?: string;
  listColumns: { key: string; label: string; type?: any }[];
  formFields: FieldConfig[];
}

export const ENTITY_CONFIGS: Record<string, EntityConfig> = {
  employees: {
    slug: 'employees',
    arabicName: 'الموظفون',
    description: 'إدارة بيانات الموظفين',
    listColumns: [
      { key: 'code', label: 'المعرّف', type: 'badge' },
      { key: 'fullName', label: 'الاسم الكامل' },
      { key: 'jobTitle', label: 'المسمى الوظيفي' },
      { key: 'department', label: 'الإدارة', type: 'badge' },
      { key: 'email', label: 'البريد الإلكتروني' },
      { key: 'status', label: 'الحالة', type: 'status' },
    ],
    formFields: [
      { key: 'fullName', label: 'الاسم الكامل', required: true },
      { key: 'jobTitle', label: 'المسمى الوظيفي' },
      { key: 'department', label: 'الإدارة', lookupCategory: 'Departments' },
      { key: 'email', label: 'البريد الإلكتروني', type: 'email' },
      { key: 'phone', label: 'الجوال', type: 'tel' },
      { key: 'hireDate', label: 'تاريخ التعيين', type: 'date' },
      { key: 'status', label: 'الحالة', lookupCategory: 'EmployeeStatus' },
      { key: 'notes', label: 'ملاحظات', type: 'textarea', cols: 2 },
    ],
  },
  
  initiatives: {
    slug: 'initiatives',
    arabicName: 'المبادرات',
    description: 'إدارة المبادرات الاستراتيجية',
    listColumns: [
      { key: 'code', label: 'المعرّف', type: 'badge' },
      { key: 'name', label: 'اسم المبادرة' },
      { key: 'category', label: 'الفئة', type: 'badge' },
      { key: 'status', label: 'الحالة', type: 'status' },
      { key: 'priority', label: 'الأولوية', type: 'badge' },
      { key: 'progress', label: 'التقدم %' },
      { key: 'budgetSar', label: 'الميزانية', type: 'currency' },
    ],
    formFields: [
      { key: 'name', label: 'اسم المبادرة', required: true, cols: 2 },
      { key: 'description', label: 'الوصف', type: 'textarea', cols: 2 },
      { key: 'category', label: 'الفئة', lookupCategory: 'IdeaCategory' },
      { key: 'status', label: 'الحالة', lookupCategory: 'InitiativeStatus' },
      { key: 'priority', label: 'الأولوية', lookupCategory: 'Priority' },
      { key: 'progress', label: 'التقدم (0-100)', type: 'number' },
      { key: 'startDate', label: 'تاريخ البدء', type: 'date' },
      { key: 'endDate', label: 'تاريخ الانتهاء', type: 'date' },
      { key: 'budgetSar', label: 'الميزانية (ر.س)', type: 'currency' },
      { key: 'actualSpendSar', label: 'الإنفاق الفعلي (ر.س)', type: 'currency' },
      { key: 'notes', label: 'ملاحظات', type: 'textarea', cols: 2 },
    ],
  },
  
  ideas: {
    slug: 'ideas',
    arabicName: 'الأفكار',
    description: 'إدارة الأفكار المقدّمة',
    listColumns: [
      { key: 'code', label: 'المعرّف', type: 'badge' },
      { key: 'title', label: 'الفكرة' },
      { key: 'category', label: 'القطاع', type: 'badge' },
      { key: 'stage', label: 'المرحلة', type: 'status' },
      { key: 'status', label: 'الحالة', type: 'status' },
      { key: 'submissionDate', label: 'التاريخ', type: 'date' },
    ],
    formFields: [
      { key: 'title', label: 'عنوان الفكرة', required: true, cols: 2 },
      { key: 'description', label: 'وصف الفكرة', type: 'textarea', cols: 2 },
      { key: 'category', label: 'القطاع', lookupCategory: 'IdeaCategory' },
      { key: 'stage', label: 'المرحلة', lookupCategory: 'IdeaStage' },
      { key: 'status', label: 'الحالة', type: 'select', options: ['جديدة', 'موافق عليها', 'مرفوضة'] },
      { key: 'submissionDate', label: 'تاريخ التقديم', type: 'date' },
      { key: 'reviewer', label: 'المراجع' },
      { key: 'impactExpected', label: 'الأثر المتوقع', type: 'textarea', cols: 2 },
      { key: 'notes', label: 'ملاحظات', type: 'textarea', cols: 2 },
    ],
  },
  
  'sandbox-applications': {
    slug: 'sandbox-applications',
    arabicName: 'طلبات الساندبوكس',
    description: 'إدارة طلبات البيئة التجريبية',
    listColumns: [
      { key: 'code', label: 'المعرّف', type: 'badge' },
      { key: 'solutionName', label: 'اسم المشروع' },
      { key: 'entityName', label: 'الجهة' },
      { key: 'solutionDomain', label: 'المجال', type: 'badge' },
      { key: 'applicationStatus', label: 'الحالة', type: 'status' },
      { key: 'submissionDate', label: 'التقديم', type: 'date' },
    ],
    formFields: [
      { key: 'solutionName', label: 'اسم الحل/المشروع', required: true, cols: 2 },
      { key: 'entityName', label: 'اسم الجهة', required: true },
      { key: 'entityType', label: 'نوع الجهة', lookupCategory: 'PartnerType' },
      { key: 'responsibleName', label: 'اسم المسؤول' },
      { key: 'jobTitle', label: 'المسمى الوظيفي' },
      { key: 'contactEmail', label: 'البريد الإلكتروني', type: 'email' },
      { key: 'contactPhone', label: 'الجوال', type: 'tel' },
      { key: 'solutionDescription', label: 'وصف الحل', type: 'textarea', cols: 2 },
      { key: 'problemStatement', label: 'بيان المشكلة', type: 'textarea', cols: 2 },
      { key: 'solutionDomain', label: 'مجال الحل', lookupCategory: 'SolutionDomain' },
      { key: 'productMaturity', label: 'مرحلة جاهزية المنتج', lookupCategory: 'ProductMaturity' },
      { key: 'vision2030Alignment', label: 'التوافق مع رؤية 2030', lookupCategory: 'Vision2030' },
      { key: 'applicationStatus', label: 'حالة الطلب', lookupCategory: 'SandboxStatus' },
      { key: 'applicationCategory', label: 'تصنيف الطلب', lookupCategory: 'SandboxCategory' },
      { key: 'submissionDate', label: 'تاريخ التقديم', type: 'date' },
      { key: 'scalingStrategy', label: 'استراتيجية التوسع', type: 'textarea', cols: 2 },
      { key: 'notes', label: 'ملاحظات', type: 'textarea', cols: 2 },
    ],
  },
  
  pilots: {
    slug: 'pilots',
    arabicName: 'التجارب التشغيلية',
    description: 'إدارة التجارب الميدانية',
    listColumns: [
      { key: 'code', label: 'المعرّف', type: 'badge' },
      { key: 'name', label: 'اسم التجربة' },
      { key: 'status', label: 'الحالة', type: 'status' },
      { key: 'startDate', label: 'البدء', type: 'date' },
      { key: 'budgetSar', label: 'الميزانية', type: 'currency' },
    ],
    formFields: [
      { key: 'name', label: 'اسم التجربة', required: true, cols: 2 },
      { key: 'description', label: 'الوصف', type: 'textarea', cols: 2 },
      { key: 'status', label: 'الحالة', lookupCategory: 'PilotStatus' },
      { key: 'budgetSar', label: 'الميزانية (ر.س)', type: 'currency' },
      { key: 'startDate', label: 'تاريخ البدء', type: 'date' },
      { key: 'endDate', label: 'تاريخ الانتهاء', type: 'date' },
      { key: 'successCriteria', label: 'معايير النجاح', type: 'textarea', cols: 2 },
      { key: 'outcome', label: 'النتيجة', type: 'textarea', cols: 2 },
    ],
  },
  
  challenges: {
    slug: 'challenges',
    arabicName: 'التحديات',
    description: 'إدارة التحديات والهاكاثونات',
    listColumns: [
      { key: 'code', label: 'المعرّف', type: 'badge' },
      { key: 'title', label: 'عنوان التحدي' },
      { key: 'category', label: 'الفئة', type: 'badge' },
      { key: 'status', label: 'الحالة', type: 'status' },
      { key: 'launchDate', label: 'الإطلاق', type: 'date' },
      { key: 'prizeAmount', label: 'الجائزة', type: 'currency' },
    ],
    formFields: [
      { key: 'title', label: 'عنوان التحدي', required: true, cols: 2 },
      { key: 'description', label: 'الوصف', type: 'textarea', cols: 2 },
      { key: 'category', label: 'الفئة', lookupCategory: 'ChallengeCategory' },
      { key: 'status', label: 'الحالة', lookupCategory: 'ChallengeStatus' },
      { key: 'launchDate', label: 'تاريخ الإطلاق', type: 'date' },
      { key: 'closingDate', label: 'تاريخ الإغلاق', type: 'date' },
      { key: 'prizeAmount', label: 'قيمة الجائزة (ر.س)', type: 'currency' },
      { key: 'expectedOutcome', label: 'النتيجة المتوقعة', type: 'textarea', cols: 2 },
    ],
  },
  
  partners: {
    slug: 'partners',
    arabicName: 'الشركاء',
    description: 'إدارة الشركاء والجهات الخارجية',
    listColumns: [
      { key: 'code', label: 'المعرّف', type: 'badge' },
      { key: 'partnerName', label: 'الشريك' },
      { key: 'partnerType', label: 'النوع', type: 'badge' },
      { key: 'partnershipStatus', label: 'الحالة', type: 'status' },
      { key: 'contactEmail', label: 'البريد' },
    ],
    formFields: [
      { key: 'partnerName', label: 'اسم الشريك', required: true, cols: 2 },
      { key: 'partnerType', label: 'النوع', lookupCategory: 'PartnerType' },
      { key: 'partnerCategory', label: 'الفئة', lookupCategory: 'PartnerCategory' },
      { key: 'partnershipStatus', label: 'الحالة', lookupCategory: 'PartnershipStatus' },
      { key: 'contactName', label: 'اسم جهة الاتصال' },
      { key: 'contactEmail', label: 'البريد الإلكتروني', type: 'email' },
      { key: 'contactPhone', label: 'الجوال', type: 'tel' },
      { key: 'country', label: 'الدولة', lookupCategory: 'Country' },
      { key: 'city', label: 'المدينة' },
      { key: 'website', label: 'الموقع الإلكتروني', type: 'url' },
      { key: 'agreementStartDate', label: 'بدء الاتفاقية', type: 'date' },
      { key: 'agreementEndDate', label: 'انتهاء الاتفاقية', type: 'date' },
      { key: 'notes', label: 'ملاحظات', type: 'textarea', cols: 2 },
    ],
  },
  
  experts: {
    slug: 'experts',
    arabicName: 'الخبراء',
    description: 'إدارة شبكة الخبراء',
    listColumns: [
      { key: 'code', label: 'المعرّف', type: 'badge' },
      { key: 'fullName', label: 'الاسم' },
      { key: 'category', label: 'الفئة', type: 'badge' },
      { key: 'specialization', label: 'التخصص' },
      { key: 'status', label: 'الحالة', type: 'status' },
    ],
    formFields: [
      { key: 'fullName', label: 'الاسم الكامل', required: true, cols: 2 },
      { key: 'category', label: 'فئة الخبير', lookupCategory: 'ExpertCategory' },
      { key: 'specialization', label: 'التخصص' },
      { key: 'email', label: 'البريد الإلكتروني', type: 'email' },
      { key: 'phone', label: 'الجوال', type: 'tel' },
      { key: 'organization', label: 'المؤسسة' },
      { key: 'jobTitle', label: 'المسمى الوظيفي' },
      { key: 'country', label: 'الدولة', lookupCategory: 'Country' },
      { key: 'city', label: 'المدينة' },
      { key: 'cvUrl', label: 'رابط السيرة الذاتية', type: 'url' },
      { key: 'linkedInUrl', label: 'LinkedIn', type: 'url' },
      { key: 'status', label: 'الحالة', lookupCategory: 'ExpertStatus' },
      { key: 'bio', label: 'نبذة', type: 'textarea', cols: 2 },
    ],
  },
  
  cems: {
    slug: 'cems',
    arabicName: 'المبتكرون',
    description: 'إدارة بيانات المبتكرين والأفراد',
    listColumns: [
      { key: 'code', label: 'المعرّف', type: 'badge' },
      { key: 'fullName', label: 'الاسم' },
      { key: 'jobTitle', label: 'المسمى' },
      { key: 'innovationField', label: 'مجال الابتكار', type: 'badge' },
      { key: 'status', label: 'الحالة', type: 'status' },
    ],
    formFields: [
      { key: 'fullName', label: 'الاسم الكامل', required: true, cols: 2 },
      { key: 'email', label: 'البريد الإلكتروني', type: 'email' },
      { key: 'phone', label: 'الجوال', type: 'tel' },
      { key: 'city', label: 'المدينة' },
      { key: 'educationLevel', label: 'المؤهل', lookupCategory: 'EducationLevel' },
      { key: 'jobTitle', label: 'المسمى الوظيفي' },
      { key: 'organization', label: 'المؤسسة' },
      { key: 'innovationField', label: 'مجال الابتكار', lookupCategory: 'IdeaCategory' },
      { key: 'status', label: 'الحالة', lookupCategory: 'CemStatus' },
    ],
  },
  
  risks: {
    slug: 'risks',
    arabicName: 'سجل المخاطر',
    description: 'إدارة وتتبع المخاطر',
    listColumns: [
      { key: 'code', label: 'المعرّف', type: 'badge' },
      { key: 'title', label: 'وصف المخاطرة' },
      { key: 'category', label: 'الفئة', type: 'badge' },
      { key: 'riskLevel', label: 'المستوى', type: 'status' },
      { key: 'status', label: 'الحالة', type: 'status' },
    ],
    formFields: [
      { key: 'title', label: 'وصف المخاطرة', required: true, cols: 2 },
      { key: 'description', label: 'تفاصيل', type: 'textarea', cols: 2 },
      { key: 'category', label: 'الفئة', lookupCategory: 'RiskCategory' },
      { key: 'likelihood', label: 'الاحتمالية (1-5)', type: 'number' },
      { key: 'impact', label: 'الأثر (1-5)', type: 'number' },
      { key: 'riskLevel', label: 'مستوى المخاطرة', lookupCategory: 'RiskLevel' },
      { key: 'status', label: 'الحالة', lookupCategory: 'RiskStatus' },
      { key: 'mitigationPlan', label: 'خطة المعالجة', type: 'textarea', cols: 2 },
      { key: 'identifiedDate', label: 'تاريخ الاكتشاف', type: 'date' },
      { key: 'reviewDate', label: 'تاريخ المراجعة', type: 'date' },
    ],
  },
  
  metrics: {
    slug: 'metrics',
    arabicName: 'المؤشرات',
    description: 'مؤشرات الأداء والنتائج',
    listColumns: [
      { key: 'code', label: 'المعرّف', type: 'badge' },
      { key: 'metricName', label: 'اسم المؤشر' },
      { key: 'category', label: 'الفئة', type: 'badge' },
      { key: 'targetValue', label: 'المستهدف' },
      { key: 'currentValue', label: 'الحالي' },
      { key: 'status', label: 'الحالة', type: 'status' },
    ],
    formFields: [
      { key: 'metricName', label: 'اسم المؤشر', required: true, cols: 2 },
      { key: 'description', label: 'الوصف', type: 'textarea', cols: 2 },
      { key: 'category', label: 'الفئة', lookupCategory: 'MetricCategory' },
      { key: 'unit', label: 'وحدة القياس' },
      { key: 'targetValue', label: 'القيمة المستهدفة', type: 'number' },
      { key: 'currentValue', label: 'القيمة الحالية', type: 'number' },
      { key: 'status', label: 'الحالة', lookupCategory: 'MetricStatus' },
      { key: 'frequency', label: 'التكرار', lookupCategory: 'MetricFrequency' },
      { key: 'measurementDate', label: 'تاريخ القياس', type: 'date' },
    ],
  },
  
  communications: {
    slug: 'communications',
    arabicName: 'التواصل والإعلام',
    description: 'إدارة الحملات الإعلامية',
    listColumns: [
      { key: 'code', label: 'المعرّف', type: 'badge' },
      { key: 'title', label: 'العنوان' },
      { key: 'channel', label: 'القناة', type: 'badge' },
      { key: 'publishDate', label: 'النشر', type: 'date' },
      { key: 'reach', label: 'الوصول' },
    ],
    formFields: [
      { key: 'title', label: 'عنوان الاتصال', required: true, cols: 2 },
      { key: 'channel', label: 'القناة', lookupCategory: 'CommunicationChannel' },
      { key: 'audience', label: 'الجمهور المستهدف', lookupCategory: 'CommunicationAudience' },
      { key: 'publishDate', label: 'تاريخ النشر', type: 'date' },
      { key: 'reach', label: 'الوصول', type: 'number' },
      { key: 'engagement', label: 'التفاعل', type: 'number' },
      { key: 'url', label: 'الرابط', type: 'url' },
      { key: 'content', label: 'المحتوى', type: 'textarea', cols: 2 },
    ],
  },
  
  documents: {
    slug: 'documents',
    arabicName: 'الوثائق',
    description: 'إدارة الوثائق والملفات',
    listColumns: [
      { key: 'code', label: 'المعرّف', type: 'badge' },
      { key: 'title', label: 'العنوان' },
      { key: 'documentType', label: 'النوع', type: 'badge' },
      { key: 'version', label: 'الإصدار' },
      { key: 'uploadDate', label: 'الرفع', type: 'date' },
    ],
    formFields: [
      { key: 'title', label: 'عنوان الوثيقة', required: true, cols: 2 },
      { key: 'documentType', label: 'النوع', lookupCategory: 'DocumentType' },
      { key: 'description', label: 'الوصف', type: 'textarea', cols: 2 },
      { key: 'fileUrl', label: 'رابط الملف', type: 'url', cols: 2 },
      { key: 'version', label: 'الإصدار' },
      { key: 'status', label: 'الحالة', lookupCategory: 'DocumentStatus' },
    ],
  },
};

export const ENTITY_SLUGS = Object.keys(ENTITY_CONFIGS);
