import { NextRequest, NextResponse } from 'next/server';

// Some clients still request /favicon.ico explicitly.
// Redirect to the app icon endpoint generated by app/icon.tsx.
export function GET(request: NextRequest) {
  return NextResponse.redirect(new URL('/icon', request.url), 308);
}
